version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    image: cscfi/imaging-beacon:latest
    restart: unless-stopped
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_CORS: ${APP_CORS}
      APP_INFO: ${APP_INFO}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_AUTH: ${DB_AUTH}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongodb
    volumes:
      - /data:/data
    ports:
      - "8080:8080"

  mongodb:
    image: 'mongo'
    container_name: mongodb
    env_file: .env
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:
    driver: local
